#' Title plot_cnv_source
#'
#' @param cnvr standard file was generated by 'call_cnvr' function, should contain the frequency of CNVR
#' @param clean_cnv standard file was generated by 'cnv_clean' function
#' @param pedigree include 'Sample_ID', 'Father_ID', 'Mother_ID', 'Country', 'Group'
#' @param Frequent_threshold Integer, indicate the frequency of CNVR
#'
#' @return CNVR source plot
#' @export plot_cnv_source
#'
plot_cnv_source <- function(cnvr, clean_cnv, pedigree, Frequent_threshold) {
  cnvr <- fread(cnvr)
  high_freq <- filter(cnvr, Frequent >= Frequent_threshold)

  for (i in 1:nrow(high_freq)){
    cnv_visual(clean_cnv = clean_cnv, chr_id = high_freq$Chr[i],
               start_position = high_freq$Start[i]/1000000, end_position = high_freq$End[i]/1000000,  report_id = 1,
               pedigree = pedigree)
  }
}
