#' Custom CNVR distribution map and plot all high frequency CNVR at once
#'
#' @param cnvr standard cnvr file was generated by 'call_cnvr' function
#' @param assembly which reference genome assembly used in the data, each chromosome has different length between various assembly, now only support Bovine UMD3.1 and ARS1.2
#' @param overlap_cnvr the common CNVRs list between two CNVR results, which use to mark underline to indicate the common CNVRs, should only contain Chr, Start and End three columns, the standard file was generated by 'compare_cnvr' function
#' @param label_prop if 'TRUE', will display the proportion of CNVRs in each chromosome
#' @param refgene reference gene list, use for plot gene
#' @param clean_cnv standard input file was generated by 'cnv_clean' function
#' @param sample_size integer, the total number of unique samples in the cnv result. combine with common_cnv_threshold to plot all CNVs which passed the threshold
#' @param common_cnv_threshold two decimal places, combine with sample_size to plot all CNVs passed the common threshold
#' @param legend_x the x coordinate of legend, relative to the maximum length of Chromosome, unit is 'Mb'
#' @param legend_y the y coordinate of legend
#' @param gain_col set color for type of gain CNVR
#' @param loss_col set color for type of loss CNVR
#' @param mixed_col set color for type of mixed CNVR
#' @param overlap_col set color for Overlapped CNVRs
#' @param chr_col set color of Chromosomes
#' @param folder set name of folder to save results
#' @param gene_font_size set the font size of gene in CNV annotation plot
#' @param width_1 number to set the width of final plot size, unit is 'cm'
#' @param height_1 number to set the height of final plot size, unit is 'cm'
#' @param col_gene set the color of Gene, only work in Gene annotated at CNV plot
#'
#' @import ggplot2 dplyr reshape2 tidyr
#'
#' @importFrom data.table fread fwrite setkey foverlaps setDT
#' @importFrom graphics barplot legend par rect text
#'
#' @return A figure of CNVR distribution map and plot parameters.
#' If given clean_cnv file, will plot all CNVRs which are passed common threshold.
#' @export cnvr_plot
#'
cnvr_plot <- function(cnvr, assembly = "ARS", overlap_cnvr = NULL, label_prop = TRUE, legend_x = 127, legend_y = 30, clean_cnv = NULL, sample_size = NULL, common_cnv_threshold = 0.05, refgene = "ARS", gain_col = "red", loss_col = "green", mixed_col ="blue", overlap_col = "purple", chr_col = "black", folder ="cnvr_plot", gene_font_size = 2.2, width_1 = 22, height_1 = 14.5, col_gene = "gray") {
  if(!file.exists(paste0(folder))){
    dir.create(paste0(folder))
    cat(paste0("A new folder '", folder, "' was created in working directory.\n"))
  }
  if (is.null(clean_cnv)) {
    #Prepare parameters for CNVR distribution plot
    #prepare the Y axis for each chromosome
    if(typeof(cnvr) == "character"){
      cnvr_plot_part <- fread(file = cnvr, header = TRUE, sep = "\t")
    } else {
      cnvr_plot_part <- cnvr
    }

    chr <- data.frame("Chr" = seq(1,max(as.integer(cnvr_plot_part$Chr))))  #generate a chr order
    chr <- chr %>%
           mutate(chr_top = (as.integer(max(cnvr_plot_part$Chr)) + 1 - Chr)*3,
                  chr_bottom = chr_top - 1.5)   #our plot depend on x and y coordinate axix, the toppest is chr 1 and bottom is chr29, interval of y axis is 3
                                                #bar plot depth is 1.5, this will using for polt rectangle for cnvr

    #chr$chr_top <- (max(cnvr_plot_part$Chr) + 1 -chr$Chr)*3 #our plot depend on x and y coordinate axix, the toppest is chr 1 and bottom is chr29, interval of y axis is 3
    #chr$chr_bottom <- chr$chr_top - 1.5 #bar plot deepth is 1.5, this will using for polt rectangle for cnvr
    #class(chr$Chr) #check the type
    chr$Chr = as.character(chr$Chr)#convert interger to charactor

    if (assembly == "UMD") {
      #UMD3.1 Chromsome Length
      chr_length <- c(51.505224, 46.312546, 45.407902, 51.681464, 42.90417, 62.71493, 52.530062,
                      61.435874, 71.599096, 72.042655, 64.057457,
                      66.004023,75.158596, 81.724687, 85.296676, 84.64839, 84.24035, 91.163125,
                      107.310763, 104.305016, 105.70825, 113.384836, 112.638659, 119.458736,
                      121.1914245, 120.829699, 121.430405, 137.060424, 158.337067)
      chr_name <- paste0("chr", seq(from = 29, to = 1, by = -1))
    } else if(assembly == "ARS"){
      # The length of X Chromsome is 139.009144 in ARS reference genome
      # ARS assembly
      chr_length <- c( 51.098607, 45.94015, 45.612108, 51.992305, 42.350435,
                       62.317253, 52.498615, 60.773035, 69.862954,
                           71.974595, 63.449741, 65.820629, 73.167244, 81.013979,
                           85.00778, 82.403003, 83.472345, 87.216183, 106.982474,
                           103.308737, 105.454467, 113.31977, 110.682743, 117.80634,
                           120.089316, 120.000601, 121.005158, 136.231102, 158.53411)
      chr_name <- paste0("chr", seq(from = 29, to = 1, by = -1))
    } else {
      #construct the border of each chromosome from imput data
      chr_length <- cnvr_plot_part %>%
                    group_by(Chr) %>%
                    summarise(length = max(End) / 1000000) %>%
                    arrange(-as.integer(Chr)) %>%
                    select(length) %>%
                    as.matrix() %>%
                    t() %>%
                    as.vector()
      chr_name <- paste0("chr", seq(from = max(as.integer(cnvr_plot_part$Chr)), to = 1, by = -1))
    }

    #4.6.1 prepare CNVPartition plot input data-----
    cnvr_plot_part$start_left <- cnvr_plot_part$Start/1000000 #convert bp to Mbp
    cnvr_plot_part$end_right <- cnvr_plot_part$End/1000000 #convert bp to Mbp
    cnvr_plot_part$Chr <- as.character(cnvr_plot_part$Chr)
    cnvr_plot_part <- merge(cnvr_plot_part, chr, all.x = TRUE)

    #customize the number of CNVRs in map by sample size
    if(!is.null(sample_size)){
      cnvr_plot_part <- filter(cnvr_plot_part, n_Sample >= sample_size * common_cnv_threshold)
    }

    fwrite(cnvr_plot_part, file = paste0(folder, "/cnvr_plot.txt"), sep ="\t", quote = FALSE)

    #this file need reread if you start from here
    #cnvr_plot_part <- fread("CNVRplot/cnvr_plot_part.txt", sep ="\t", quote = FALSE)
    gain_part <- cnvr_plot_part[cnvr_plot_part$Type == "Gain", ]
    loss_part <- cnvr_plot_part[cnvr_plot_part$Type == "Loss", ]
    mixed_part <- cnvr_plot_part[cnvr_plot_part$Type == "Mixed", ]


    #4.6.2 start make cnvr plot for CNVPartition
    png(filename = paste0(folder, "/cnvr_plot.png"),
        res = 350,
        width = width_1, height = height_1, units = "cm", bg = "transparent")

    #setting the graphic parameter
    par(lab=c(max(cnvr_plot_part$Chr),max(cnvr_plot_part$Chr),3),las=1,yaxt="s",xaxt="s",mar=c(7,7,4,6))

    #draw a bar plot and setup each bar name
    bar <- barplot(chr_length, horiz=TRUE,width=1.5,space=1,xlim=c(0,max(chr_length)+6),
                   names.arg= chr_name,
                   col=c("white"), border = chr_col, xlab="Physical Position (Mbp)",cex.name=0.8)

    #read the gain type file, each file need prepare four columns as following order: start_left, end_right, chr_top and chr_bottom
    rect(xleft = gain_part$start_left, ybottom = gain_part$chr_bottom, xright = gain_part$end_right, ytop = gain_part$chr_top, col = gain_col, border = gain_col)

    #read the loss type file and draw a rectangle shape for each CNVR and color to green
    #loss <- cnvr_plot_part[cnvr_plot_part$Type == 'LOSS']
    rect(xleft = loss_part$start_left, ybottom = loss_part$chr_bottom, xright = loss_part$end_right, ytop = loss_part$chr_top, col = loss_col, border = loss_col)

    #read the mixed file and plot rectangle as red
    #mixed <- cnvr_plot_part[cnvr_plot_part$Type == 'mixed']
    rect(xleft = mixed_part$start_left, ybottom = mixed_part$chr_bottom, xright = mixed_part$end_right, ytop = mixed_part$chr_top, col = mixed_col, border = mixed_col)

    #condition. add summary label for each chromosome
    if(label_prop == "TRUE"){
      # chr_len_max <- cnvr_plot_part %>%
      #                group_by(Chr) %>%
      #                summarise(length = max(End) / 1000000)

      chr_len_max <- data.frame("Chr" = seq(from = max(as.integer(cnvr_plot_part$Chr)), to = 1, by = -1), "Length" = chr_length)
      chr_len_max$Chr <- as.character(chr_len_max$Chr)

      chr_label <- cnvr_plot_part %>%
                   group_by(Chr) %>%
                   summarise(total_len = sum(Length) / 1000000) %>%
                   left_join(chr) %>%
                   left_join(chr_len_max) %>%
                   mutate(Len_prop = paste0(round(total_len * 100 / Length, digits = 1), "%"))

      text(x = chr_label$Length + 3, y = chr_label$chr_bottom + 0.5, labels = chr_label$Len_prop, cex=0.5)
    }


    #prepare Y axis for CNVPartition overlap region, mark a under line on the overlap region
    if(!is.null(overlap_cnvr)){
      if(typeof(overlap_cnvr) == "character"){
        overlap <- fread(file = overlap_cnvr, header = TRUE, sep = "\t")
      } else {
        overlap <- overlap_cnvr
      }
      overlap$Chr <- as.character(overlap$Chr)
      overlap <- merge(x = overlap, y = chr, all.x = TRUE)

      #condition, check if overlap CNVRs in original CNVR list? Only plot which are overlapped to original lists
      cnvr_plot_part <- setDT(cnvr_plot_part)
      setkey(cnvr_plot_part, Chr, Start, End)
      overlap <- foverlaps(x = overlap, y = cnvr_plot_part, by.x = c("Chr", "Start", "End"), type = "any", nomatch = NULL)

      overlap$start_left <- overlap$Start / 1000000
      overlap$end_right <- overlap$End / 1000000
      overlap$chr_bottom <- overlap$chr_bottom - 0.5
      overlap$chr_top <- overlap$chr_top - 1.7
      overlap$Type <- "Overlap"
      rect(xleft = overlap$start_left, ybottom = overlap$chr_bottom, xright = overlap$end_right, ytop = overlap$chr_top, col = overlap_col, border = overlap_col)

      #add legend
      legend(legend_x, legend_y,c("Gain","Loss","Mixed", "Overlap"), pch = c(15, 15, 15, 15),
             col =c(gain_col, loss_col, mixed_col, overlap_col), bty = "n", cex=0.8)
    } else {
      #add legend
      legend(legend_x, legend_y,c("Gain","Loss","Mixed"), pch = c(15, 15, 15),
             col =c(gain_col, loss_col, mixed_col), bty = "n", cex=0.8)
    }

    #title(main = "CNVR Distribution on Population Level")

    dev.off()

    if (file.exists(paste0(folder, "/cnvr_plot.png"))) {
      print("Task done, CNVR Distribution Plot saved in working directory.")
    } else {
      print("Task faild, please check your CNVR input file carefully, the input cnvr file should be the CNVR results generated from call_cnvr function")
    }
  }



  else {
    cnvr <- fread(file = cnvr) # read cnvr result from call_cnvr function
    # high_freq <- cnvr[which(cnvr[, cnvr$Frequent >= sample_size * 0.05]), ] #call common CNVRs
    high_freq <- filter(cnvr, n_Sample >= sample_size * common_cnv_threshold)
    print(paste0("There ", nrow(high_freq), " high frequency CNVR passed the customized threshold."))
    for (i in 1:nrow(high_freq)) {
      print(paste0("Ploting CNVR ", i, "..." ))
      cnv_visual(clean_cnv = clean_cnv, chr_id = high_freq$Chr[i], start_position = high_freq$Start[i]/1000000, end_position = high_freq$End[i]/1000000, refgene = refgene, folder = folder, gene_font_size = gene_font_size, height_1 = height_1, width_1 = width_1, col_gene = col_gene)
    }
  }
}

