
utils::globalVariables(c(".", "..count..", "ARS_Density", "B Allele Freq", "CNVR_ID", "CNV_Number", "CNV_Value", "Check_gene", "Check_overlap",
                         "Chr", "Chr_TAR", "Chr_DEF", "Chr_def", "Chr_tar", "Common_Gene", "Common_check", "Difference", "End", "End_2", "End_TAR",
                         "End_ARS_Map", "End_Match", "End_DEF", "End_win", "Frequency_1", "Frequency_2", "Frequency_3", "Frequency_4", "Frequent",
                         "Group", "Herd", "ID", "Length", "Log R Ratio", "Match", "Mb_tar", "Name", "Order", "Overlap_length", "Position_def",
                         "Position_tar", "SNP_Freq_def", "SNP_Freq_tar", "Sample_ID", "Sample_ID_TAR", "Sample_ID_DEF", "Sire_ID", "Sire_Source",
                         "Start", "Start_2", "Start_TAR", "Start_ARS_Map", "Start_Match", "Start_DEF", "Start_win", "Type", "UMD_Density", "V1",
                         "V2", "V3", "V4", "V5", "V6", "V7", "V8", "callrate", "data.table", "g_End", "g_Start", "gene_name", "group", "hz", "i.End",
                         "i.Start", "n_CNV", "name2", "name2_1", "num", "num_CNVR", "num_gene", "number_roh", "origi_length", "overlap_len", "percent_group",
                         "percent_total", "pos", "prop_overlap_len", "prop_roh", "three_gene_summary", "total_length", "value", "variable", "window_id",
                         "x", "y", "y_max", "y_min", "Frequency", "chr_top", "all_of", "name", "gene", "CNV_Start", "CNV_End", "SNP Name", "Var1", "Var2",
                         "End_def", "End_tar", "Start_def", "Start_tar", "converted_len", "length_diff", "original_len", "qc_check","Freq","Haplotype",
                         "Re_code","Recode_Type", "Length_def", "Length_tar", "def_Density", "tar_Density", "Haploid", "n_Sample", "total_len", "Pos",
                         "bins", "max_edge", "sd", "group_color", "num_gene_2", "key", "POS", "REF", "ALT", "QUAL", "FILTER", "INFO", "FORMAT",
                         "Length_group", "number_sample", "Interval_ID"))
